name: Cross-Platform Package Tests

on: 
  push:
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        stability: [prefer-lowest, prefer-stable]
        include:
          - laravel: 8
            testbench: 6
            php: [7.4, 8.0, 8.1]
          - laravel: 9
            testbench: 7
            php: [8.0, 8.1, 8.2]
          - laravel: 10
            testbench: 8
            php: [8.1, 8.2, 8.3]
          - laravel: 11
            testbench: 9
            php: [8.2, 8.3, 8.4]

    steps:
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, json, xml
          coverage: none

      - name: Check out code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          composer require --no-update laravel/framework:${{ matrix.laravel }}.*
          composer require --no-update orchestra/testbench:${{ matrix.testbench }}.*
          composer update --${{ matrix.stability }} --prefer-dist --no-interaction

      - name: Run tests with Pest
        run: vendor/bin/pest
